# -*- coding: utf-8 -*-
"""student_gradebook_projectt6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--mZEQfSTgzpAjDUvk2586TVuOwM3V2T
"""

# Commented out IPython magic to ensure Python compatibility.
# %%markdown
# # Week6:Student Gradebook App
# ##_student name:FATIMA ZOHRA_
# ###This project store student marks and grades in a CSV file.
#

import csv
file_name="student_gradebook.csv"

try:
  with open(file_name,"r",newline="")as file:
    pass
except FileNotFoundError:
  with open(file_name,"w",newline="")as file:
    writer=csv.writer(file)
    writer.writerow(["Student Name","Subject","Marks","Grade"])
    print("Gradebook file created successfully.")

import csv

file_name = "student_gradebook.csv"


def calculate_grade(marks):
  if marks >= 90:
    return "A+"
  elif marks >= 80:
    return "A"
  elif marks >= 70:
    return "B"
  elif marks >= 60:
    return "C"
  elif marks >= 50:
    return "D"
  else:
    return "F"


def add_student():
  try:
    name = input("Enter student name: ").strip()
    subject = input("Enter subject: ").strip()

    if name == "" or subject == "":
      raise ValueError("Name and subject cannot be empty.")

    marks = float(input("Enter marks: "))

    if marks < 0 or marks > 100:
      raise ValueError("Marks must be between 0 and 100.")

    grade = calculate_grade(marks)

    with open(file_name, "a", newline="") as file:
      writer = csv.writer(file)
      writer.writerow([name, subject, marks, grade])
      print(f"Student record added successfully.\nGrade: {grade}")

  except ValueError as error:
    print("Error:", error)

