# -*- coding: utf-8 -*-
"""week_4_utlillity_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bm8O7ZrEW1dqOArFdSh4rrkaDjjQozYI
"""

# Commented out IPython magic to ensure Python compatibility.
# %%markdown
# #*week 4 utility project*
# ##```student name:FATIMA ZOHRA```
# ###_Functions:Factorial,Prime check,Square Root_

# Commented out IPython magic to ensure Python compatibility.
# %%writefile utility.py
# import math
# 
# def factorial(number):
#     result=1
#     for value in  range(1,number+1):
#         result*=value
#     return result
# def prime_check(number):
#     if number < 2:
#        return False
#     for value in range(2,number):
#         if number % value == 0:
#             return False
#     return True
# def square_root(number):
#     return math.sqrt(number)

import utility

print("factorial of 5:",utility.factorial(5))

print("is 7 prime number?:",utility.prime_check(7))

print("Square root of 25:",utility.square_root(25))

print("=====UTILITY PROGRAM=====")
# factorial
factorial_number=int(input("Enter a number to find its factorial:"))
if factorial_number<0:
  print("Factorial cannot be found for negative numbers")
else:
  ans=utility.factorial(factorial_number)
  print("factorial is",ans)
  #prime number check
prime_number=int(input("Enter a number to check if it is a prime number:"))
if utility.prime_check(prime_number)==True:
  print(prime_number,"is a prime number")
else:
  print(prime_number,"is not a prime number")
  #square root
square_root_number=int(input("Enter a number to find its square root:"))
if square_root_number<0:
  print("Square root cannot be found for negative numbers")
ans=utility.square_root(square_root_number)
print("Square root is",ans)

